spring:
    application:
        name: AutoDone-Executor
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/test
server:
    port: 8080
    contextPath: /UserManagementMaven

db:
    url: jdbc:mysql://localhost:3306/mysql
    userName: root
    passWord: root